### ISSUE TITLE
macos Unsupported spec Error

### ISSUE THREAD

**Issue by gboie** [sayyid5416/pyinstaller#4] opened 2023-03-12 16:22 UTC
Great work! I have this action that runs perfectly on windows-latest and ubuntu-latest, but fails to run on macos-latest with:
Run sayyid5416/pyinstaller@v1
  with:
    python_ver: 3.10
    spec: ui.py
    requirements: requirements.txt
    upload_exe_with_name: s3backup
    options: --onefile, --name "s3backup", --windowed
    exe_path: ./dist
Run python "/Users/runner/work/_actions/sayyid5416/pyinstaller/v1/src/checks.py"
  python "/Users/runner/work/_actions/sayyid5416/pyinstaller/v1/src/checks.py"
  shell: /bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    spec: ui.py
    upload_exe_with_name: s3backup
  File "/Users/runner/work/_actions/sayyid5416/pyinstaller/v1/src/checks.py", line 25
    f"Unsupported input 'spec = {spec}' was provided. Supported types: {', '.join(supported_spec)}",
                                                                                                  ^
SyntaxError: invalid syntax

My action:
jobs:
  pyinstaller-build:
    runs-on: ${{ matrix.os }} 
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.10'
          spec: 'ui.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 's3backup'
          options: --onefile, --name "s3backup", --windowed

**Comment by sayyid5416** [comment] 2023-03-12 17:22
I'll look into this. Can you provide all the logs in proper format **or** any minimal reproducible example?

**Comment by AnnoyingRain5** [comment] 2023-05-15 10:51
I just had the same issue, here are my logs @sayyid5416 
[logs_13.zip](https://github.com/sayyid5416/pyinstaller/files/11476993/logs_13.zip)

**Comment by AnnoyingRain5** [comment] 2023-05-15 10:54
Fails under MacOS-latest but works under the macos-13 beta image.

**Comment by sayyid5416** [comment] 2023-05-17 05:26
@AnnoyingRain5 Can you provide the link of the workflow where it failed instead of providing the zip file? It will help diagnosing the issue faster.

**Comment by AnnoyingRain5** [comment] 2023-05-18 01:26
@sayyid5416

[workflow yaml file](https://github.com/AnnoyingRain5/Relink-Client/blob/5772ab730b720c8e079c09fdd45f13d02b480811/.github/workflows/pyinstaller-MacOS.yml)

[Workflow run](https://github.com/AnnoyingRain5/Relink-Client/actions/runs/4979435904)

I believe this could be due to an outdated version of python being shipped with MacOS, I have run into similar issues with this in the past.

**Comment by sayyid5416** [comment] 2023-05-18 02:33
@AnnoyingRain5 It says `SyntaxError`, but there is no syntax error in `checks.py`.

> I believe this could be due to an outdated version of python being shipped with MacOS

Can you try with lower python versions like 3.10 or 3.9?

**Comment by AnnoyingRain5** [comment] 2023-05-18 02:38
Python versions below 3.10 do not support f-strings, the python version shipped with that version of macOS is below 3.10 AFAIK.

**Comment by sayyid5416** [comment] 2023-05-18 04:14
@AnnoyingRain5 If I can understand it properly, this issue is not specific to this pyinstaller action That's why I'm closing this issue now.

Also f-strings were added in version 3.6.

**Comment by AnnoyingRain5** [comment] 2023-05-18 04:19
This issue would be fixed if your script installed the latest version of python before attempting to run checks.py

**Comment by sayyid5416** [comment] 2023-05-18 04:34
@AnnoyingRain5 Can you run some tests with [test branch](https://github.com/sayyid5416/pyinstaller/tree/test). I've done changes you asked for.

**Comment by AnnoyingRain5** [comment] 2023-05-18 04:50
Works great, thanks!

https://github.com/AnnoyingRain5/Relink-Client/actions/runs/5010618603

**Comment by sayyid5416** [comment] 2023-05-18 05:00
@AnnoyingRain5 It would be great if you could test with few more different types of configurations on different machines like windows, Ubuntu and MacOS

**Comment by AnnoyingRain5** [comment] 2023-05-18 05:01
> Also f-strings were added in version 3.6.

Oops, I was thinking of match statements, but... wouldn't that mean that macos-latest has a version older than 3.6? Wow.

> @AnnoyingRain5 It would be great if you could test with few more different types of configurations on different machines like windows, Ubuntu and MacOS

I'll do some better tests later today, thanks!

**Closed as completed** 2023-05-19 06:14 UTC
